#GitHub Action OverFlows
name: Laravel-Unit-Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-unit-tests:

    runs-on: ubuntu-latest
    #sets up the PHP environment required for running the Laravel application's tests
    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.2'
    #checks out the latest version of the code from the main branch of the repository.
    - uses: actions/checkout@v3
    #Copy ENV file ensure .env file exists in the project, If not then it create
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    #Install Dependency
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    #Generate Key For Application
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      #     - name: Create Database
      #       run: |
      #         mkdir -p database
      #         touch database/database.sqlite
      #    Execute Test Case
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: ":memory:"
      run: ./vendor/bin/pest
